# Generated by Django 5.0.8 on 2024-08-07 08:09

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(max_length=100)),
                ('TelephoneNumber', models.PositiveBigIntegerField()),
                ('Age', models.PositiveIntegerField()),
                ('Gender', models.CharField(max_length=6)),
                ('MaritalStatus', models.CharField(max_length=10)),
                ('EmailAddress', models.EmailField(blank=True, max_length=254, null=True)),
                ('Nationality', models.CharField(max_length=100)),
                ('IdentificationNumber', models.CharField(max_length=100)),
                ('settlement', models.CharField(blank=True, max_length=255, null=True)),
                ('district_city', models.CharField(blank=True, max_length=255, null=True)),
                ('subcounty_division', models.CharField(blank=True, max_length=255, null=True)),
                ('parish_ward', models.CharField(blank=True, max_length=255, null=True)),
                ('village_cell_zone', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('year_of_establishment', models.DateField()),
                ('sector', models.CharField(max_length=255)),
                ('number_of_employees_male', models.IntegerField()),
                ('number_of_employees_female', models.IntegerField()),
                ('total_employees', models.IntegerField()),
                ('revenue_per_annum', models.DecimalField(decimal_places=2, max_digits=12)),
                ('location_address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Confirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='TradeAssociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_group', models.CharField(max_length=255)),
                ('website_link', models.URLField(blank=True, null=True)),
                ('is_registered', models.BooleanField()),
                ('contact_person_name', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_person_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('contact_person_email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WomenEntrepreneurshipPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('how_did_you_hear', models.CharField(max_length=50)),
                ('preferred_communication_method', models.CharField(max_length=50)),
                ('involved_in_empowerment', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='TradeAssociationMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=10)),
                ('trade_association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='webform.tradeassociation')),
            ],
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=200)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('mobile', models.PositiveBigIntegerField(validators=[django.core.validators.MaxValueValidator(999999999999)])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
