# Generated by Django 5.0.8 on 2024-08-08 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webform', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backgroundinformation',
            name='IdentificationNumber',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
