# Generated by Django 5.0.8 on 2024-08-08 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webform', '0002_alter_backgroundinformation_identificationnumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='backgroundinformation',
            old_name='IdentificationNumber',
            new_name='Refugee_Number',
        ),
        migrations.AddField(
            model_name='backgroundinformation',
            name='Ugandan_Identification_Number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
