# Generated by Django 5.0.8 on 2024-08-08 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webform', '0005_business_user_confirmation_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='year_of_establishment',
            field=models.PositiveIntegerField(),
        ),
    ]
