# Generated by Django 5.0.8 on 2024-08-08 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webform', '0006_alter_business_year_of_establishment'),
    ]

    operations = [
        migrations.AddField(
            model_name='womenentrepreneurshipplatform',
            name='confirmed',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Confirmation',
        ),
    ]
